### PR TITLE
Added badges endpoint to pydiscourse

### PR DESCRIPTION
**Pull request by msfernandes**
Hi!

I'm using pydiscourse to consume Discourse API, but I saw that Badges endpoint isn't in pydiscourse. Then I made it! :)

### CODE REVIEW

**Comment by msfernandes** [comment]
This PR is not yet complete...
I saw right now that are others endpoints that aren't documented. So, I'll add this endpoints and comment here again, when I finished

**Comment by msfernandes** [comment]
Done :)

**Comment by bennylope** [comment]
Thanks! Hopefully will have a chance to publish a new release over lunch today.

The arguments in the docstrings should be described, but given the state of the project I'm not going to _not_ merge this b/c those are empty.

**Comment by bennylope** [comment]
This is in 0.5.0 now, thanks for pushing this!

**Pull request merged**
